spring.application.name=exercicio-sb
spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

spring.datasource.initialization-mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


